---
- name: Configure Apache.
  lineinfile:
    dest: "{{ apache_server_root }}/ports.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: apache_ports_configuration_items
  notify: restart apache

- name: Enable Apache mods.
  file:
    src: "{{ apache_server_root }}/mods-available/{{ item }}"
    dest: "{{ apache_server_root }}/mods-enabled/{{ item }}"
    state: link
  with_items: apache_mods_enabled
  notify: restart apache

- name: Add configuration.
  template: 
    src: "{{ item.src }}"
    dest: "{{ apache_server_root }}/conf-available/{{ item.dest }}"
  with_items: add_apache_conf
  when: add_apache_conf is defined

- name: Enable Apache configurations.
  file:
    src: "{{ apache_server_root }}/conf-available/{{ item }}"
    dest: "{{ apache_server_root }}/conf-enabled/{{ item }}"
    state: link
  with_items: apache_conf_enabled
  notify: restart apache
  when: apache_conf_enabled is defined

- name: Add apache vhosts configuration.
  template:
    src: "vhosts-{{ apache_vhosts_version }}.conf.j2"
    dest: "{{ apache_conf_path }}/sites-available/vhosts.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts

- name: Create vhost document roots
  file: 
    path: "{{ item.documentroot }}"
    state: directory
    owner: "{{ apache_user }}"
    group: "{{ apache_user }}"
    mode: 2775
  with_items: apache_vhosts
  when: apache_create_vhosts

- name: Check vhosts file
  stat: path="{{ apache_conf_path }}/sites-available/vhosts.conf"
  register: check_vhosts

- name: Add vhost symlink in sites-enabled.
  file:
    src: "{{ apache_conf_path }}/sites-available/vhosts.conf"
    dest: "{{ apache_conf_path }}/sites-enabled/vhosts.conf"
    state: link
  when: check_vhosts.stat.exists

- name: Check default site vhosts file
  stat: path="{{ apache_conf_path }}/sites-available/000-default.conf"
  register: check_default_vhost
  when: not check_vhosts.stat.exists

- name: Add default site symlink in sites-enabled.
  file:
    src: "{{ apache_conf_path }}/sites-available/000-default.conf"
    dest: "{{ apache_conf_path }}/sites-enabled/000-default.conf"
    state: link
  when: not check_vhosts.stat.exists and check_default_vhost.stat.exists
